name: lint

on: [ push, pull_request ]

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: DoozyX/clang-format-lint-action@v0.18.1
        with:
          source: './src'
          inplace: True
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix code style issues with clang-format
